### ISSUE TITLE
Problem launching motion control activities

### ISSUE THREAD

**Issue by biancofla** [myyerrol/learning_moveit#2]
Hi. I encounter some issues in launch of the motion control activities. I take some shots of example.

![screen_1](https://user-images.githubusercontent.com/33801756/43991097-94360ec6-9d65-11e8-8bfa-bfd485ebffed.png)
![screen_2](https://user-images.githubusercontent.com/33801756/43991098-945ab4ba-9d65-11e8-8617-8795ddbf3613.png)

**Comment by myyerrol** [comment]
@biancofla Ok, I did forget something important! I have written a script file `setup.sh`, you need to use  `git pull` command to get lastest repository and following [Installation steps](https://github.com/myyerrol/learning_moveit#2-installation) to fix the problems you mentioned.
