### ISSUE TITLE
How to run pick and place demo??

### ISSUE THREAD

**Issue by mvish7** [myyerrol/learning_moveit#4]
Hello,

I could run roslaunch panda_bringup panda_bringup_gazebo_and_moveit.launch to spawn panda arm in gazebo and start rviz.
In panda_moveit_control i can see panda_moveit_pick_place_object.cpp, but i didn't find any launch file for to launch this node.

can you please tell how to run this pick and place demo?

**Comment by myyerrol** [comment]
You can try following command: `rosrun panda_moveit_control panda_moveit_pick_place_object`.

**Comment by mvish7** [comment]
Hello,

I tried to run  

> roslaunch panda_bringup panda_bringup_gazebo_and_moveit.launch
> rosrun panda_moveit_control panda_moveit_pick_place_object

In Gazebo something like below image

![p_n_p](https://user-images.githubusercontent.com/44236845/54443279-97b1c600-4740-11e9-94cd-4bbda8982206.png)

I also checked the code, i didn't find any function to open and close gripper joints. (Please correct me if i'm wrong).

I see that in [notes](https://github.com/myyerrol/learning_moveit#4-notes) section of your post you have mentioned about gazebo object pick up issue, can you provide the code to reproduce that issue??

The thing is i'm also implementing pick and place using panda + gazebo +moveit and i'm stuck at opening gripper part. If you could share your code to operate with gripper joints then it would be great help for me.

**Comment by myyerrol** [comment]
Sorry, I'm not studying the robotic arm anymore, I can't answer your question, but you can go to the official website to see if there are any similar tutorials.
